\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename libbinio.info
@include version.texi
@settitle Binary I/O Streams Class Library @value{VERSION}
@c %**end of header

@copying
This manual documents the binary I/O streams class library version
@value{VERSION}. It was last updated on @value{UPDATED}.

Copyright @copyright{} 2002 Simon Peter

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled ``GNU Free Documentation License.''

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end quotation
@end copying

@titlepage
@title Binary I/O Streams Class Library
@subtitle Version @value{VERSION}
@subtitle Last updated on @value{UPDATED}
@author Simon Peter

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Binary I/O Streams Class Library

@insertcopying
@end ifnottex

@menu
* Introduction::                Introduction to the library.
* Copying This Manual::         Your rights and freedoms.
* Index::                       Complete index.
@end menu

@node Introduction
@chapter Introduction
@cindex Introduction

This is the introduction...

@node Copying This Manual
@appendix Copying This Manual

@menu
* GNU Free Documentation License::  License for copying this manual.
@end menu

@include fdl.texi

@node Index
@unnumbered Index

@printindex cp

@shortcontents

@bye
